In [31]:
%matplotlib inline

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn as skl
from warnings import simplefilter
# ignore all future warnings
simplefilter(action='ignore', category=FutureWarning)

In [32]:
df=pd.read_csv("water_hh_all.csv", low_memory=False)

In [33]:
df.head(5)

,Unnamed: 0,DHSID,GEID,country code and phase,year of interview,URBAN_RURA,region,source of drinking water (simplified),time to get to water source (minutes),location of source for water,anything done to water to make safe to drink,source of drinking water (categorized by type),source of drinking water (weights),water shortages,PCA w_location_weighting all,source of drinking water (categorized piped),source of drinking water (categorized piped 2),source of drinking water (categorized piped 3)
0,0,AO201100000001,AOGE61FL,AO5,2011.0,U,mesoendemica estavel,piped into dwelling,NaN,NaN,NaN,piped,5.0,NaN,-3.128714,piped into dwelling,piped into dwelling,piped into dwelling
1,1,AO201100000001,AOGE61FL,AO5,2011.0,U,mesoendemica estavel,piped into dwelling,NaN,NaN,NaN,piped,5.0,NaN,-3.128714,piped into dwelling,piped into dwelling,piped into dwelling
2,2,AO201100000001,AOGE61FL,AO5,2011.0,U,mesoendemica estavel,piped into dwelling,NaN,NaN,NaN,piped,5.0,NaN,-3.128714,piped into dwelling,piped into dwelling,piped into dwelling
3,3,AO201100000001,AOGE61FL,AO5,2011.0,U,mesoendemica estavel,piped into dwelling,NaN,NaN,NaN,piped,5.0,NaN,-3.128714,piped into dwelling,piped into dwelling,piped into dwelling
4,4,AO201100000001,AOGE61FL,AO5,2011.0,U,mesoendemica estavel,piped into dwelling,NaN,NaN,NaN,piped,5.0,NaN,-3.128714,piped into dwelling,piped into dwelling,piped into dwelling

In [34]:
df.shape

(970636, 18)

# dropping columns

In [35]:
df.drop(['Unnamed: 0', 'DHSID','GEID'], axis=1, inplace=True)

In [36]:
df.head(5)

,country code and phase,year of interview,URBAN_RURA,region,source of drinking water (simplified),time to get to water source (minutes),location of source for water,anything done to water to make safe to drink,source of drinking water (categorized by type),source of drinking water (weights),water shortages,PCA w_location_weighting all,source of drinking water (categorized piped),source of drinking water (categorized piped 2),source of drinking water (categorized piped 3)
0,AO5,2011.0,U,mesoendemica estavel,piped into dwelling,NaN,NaN,NaN,piped,5.0,NaN,-3.128714,piped into dwelling,piped into dwelling,piped into dwelling
1,AO5,2011.0,U,mesoendemica estavel,piped into dwelling,NaN,NaN,NaN,piped,5.0,NaN,-3.128714,piped into dwelling,piped into dwelling,piped into dwelling
2,AO5,2011.0,U,mesoendemica estavel,piped into dwelling,NaN,NaN,NaN,piped,5.0,NaN,-3.128714,piped into dwelling,piped into dwelling,piped into dwelling
3,AO5,2011.0,U,mesoendemica estavel,piped into dwelling,NaN,NaN,NaN,piped,5.0,NaN,-3.128714,piped into dwelling,piped into dwelling,piped into dwelling
4,AO5,2011.0,U,mesoendemica estavel,piped into dwelling,NaN,NaN,NaN,piped,5.0,NaN,-3.128714,piped into dwelling,piped into dwelling,piped into dwelling

# dropping more columns

In [37]:
df.drop(['anything done to water to make safe to drink','source of drinking water (weights)','water shortages', 'PCA w_location_weighting all','source of drinking water (categorized piped)','source of drinking water (categorized piped 2)', 'source of drinking water (categorized piped 3)'],axis=1, inplace=True)

In [38]:
df.shape

(970636, 8)

# one-hot encoding

In [39]:
from sklearn.preprocessing import OneHotEncoder

In [40]:
from category_encoders.one_hot import OneHotEncoder

In [41]:
#creating instance of one-hot encoder
encoder=OneHotEncoder(handle_unknown='ignore')

In [42]:
ohe=OneHotEncoder(use_cat_names=True)
df_source=ohe.fit_transform(df['source of drinking water (simplified)'])

In [43]:
df_source

,source of drinking water (simplified)_piped into dwelling,source of drinking water (simplified)_piped to yard/plot,source of drinking water (simplified)_public tap/standpipe,source of drinking water (simplified)_protected spring,source of drinking water (simplified)_street vendor,source of drinking water (simplified)_surface water,source of drinking water (simplified)_protected well,source of drinking water (simplified)_unprotected well,source of drinking water (simplified)_unprotected spring,source of drinking water (simplified)_bottled,source of drinking water (simplified)_Tube well or borehole,source of drinking water (simplified)_rainwater,source of drinking water (simplified)_other,source of drinking water (simplified)_piped to neighbor,source of drinking water (simplified)_nan,source of drinking water (simplified)_sachet
0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970631,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
970632,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
970633,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
970634,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
970635,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0

In [44]:
df_time=df['time to get to water source (minutes)']

In [45]:
df_time

0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
          ...
970631     0.0
970632     0.0
970633    10.0
970634     0.0
970635    10.0
Name: time to get to water source (minutes), Length: 970636, dtype: float64

In [46]:
df_location=df['location of source for water']

In [47]:
df_location

0                      NaN
1                      NaN
2                      NaN
3                      NaN
4                      NaN
                ...
970631    in own yard/plot
970632    in own yard/plot
970633           elsewhere
970634    in own yard/plot
970635           elsewhere
Name: location of source for water, Length: 970636, dtype: object

In [48]:
dataset_one=[df_source,df_time,df_location]

In [49]:
df_new=pd.concat(dataset_one,axis=1, join='inner')

In [50]:
df_new

,source of drinking water (simplified)_piped into dwelling,source of drinking water (simplified)_piped to yard/plot,source of drinking water (simplified)_public tap/standpipe,source of drinking water (simplified)_protected spring,source of drinking water (simplified)_street vendor,source of drinking water (simplified)_surface water,source of drinking water (simplified)_protected well,source of drinking water (simplified)_unprotected well,source of drinking water (simplified)_unprotected spring,source of drinking water (simplified)_bottled,source of drinking water (simplified)_Tube well or borehole,source of drinking water (simplified)_rainwater,source of drinking water (simplified)_other,source of drinking water (simplified)_piped to neighbor,source of drinking water (simplified)_nan,source of drinking water (simplified)_sachet,time to get to water source (minutes),location of source for water
0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
3,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
4,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970631,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0.0,in own yard/plot
970632,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0.0,in own yard/plot
970633,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,10.0,elsewhere
970634,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0.0,in own yard/plot
970635,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,10.0,elsewhere

In [51]:
df_new.head()

,source of drinking water (simplified)_piped into dwelling,source of drinking water (simplified)_piped to yard/plot,source of drinking water (simplified)_public tap/standpipe,source of drinking water (simplified)_protected spring,source of drinking water (simplified)_street vendor,source of drinking water (simplified)_surface water,source of drinking water (simplified)_protected well,source of drinking water (simplified)_unprotected well,source of drinking water (simplified)_unprotected spring,source of drinking water (simplified)_bottled,source of drinking water (simplified)_Tube well or borehole,source of drinking water (simplified)_rainwater,source of drinking water (simplified)_other,source of drinking water (simplified)_piped to neighbor,source of drinking water (simplified)_nan,source of drinking water (simplified)_sachet,time to get to water source (minutes),location of source for water
0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
3,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
4,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN

# multi-linear regression

location of source of water(output)= B0+source of drinking water*B1+....+time to get to water source(minutes)*B_n+e

In [52]:
#setting input and output variables

In [53]:
x=df_new.drop('location of source for water', axis=1)

In [54]:
x

,source of drinking water (simplified)_piped into dwelling,source of drinking water (simplified)_piped to yard/plot,source of drinking water (simplified)_public tap/standpipe,source of drinking water (simplified)_protected spring,source of drinking water (simplified)_street vendor,source of drinking water (simplified)_surface water,source of drinking water (simplified)_protected well,source of drinking water (simplified)_unprotected well,source of drinking water (simplified)_unprotected spring,source of drinking water (simplified)_bottled,source of drinking water (simplified)_Tube well or borehole,source of drinking water (simplified)_rainwater,source of drinking water (simplified)_other,source of drinking water (simplified)_piped to neighbor,source of drinking water (simplified)_nan,source of drinking water (simplified)_sachet,time to get to water source (minutes)
0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN
1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN
2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN
3,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN
4,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970631,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0.0
970632,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0.0
970633,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,10.0
970634,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0.0
970635,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,10.0

In [55]:
y=df_new['location of source for water']

In [56]:
y

0                      NaN
1                      NaN
2                      NaN
3                      NaN
4                      NaN
                ...
970631    in own yard/plot
970632    in own yard/plot
970633           elsewhere
970634    in own yard/plot
970635           elsewhere
Name: location of source for water, Length: 970636, dtype: object

In [57]:
#splitting the dataset
from sklearn.linear_model import LinearRegression

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.3,random_state=100)

In [58]:
#multiple linear regression model

#creating linear regression instance 'mlr'
mlr=LinearRegression()
mlr.fit(x_train,y_train)

ValueError: Input X contains NaN.
LinearRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

# KNN imputer

In [59]:
from sklearn.impute import KNNImputer

In [67]:
imputer = KNNImputer(n_neighbors=2, weights="uniform")
df_new_x=pd.DataFrame(imputer.fit_transform(x)) #imputed x

In [77]:
df_new_x

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970631,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
970632,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
970633,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0
970634,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
970635,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0

In [82]:
value = df_new_x.isnull().values.any()
print(value) #no missing values

False

In [83]:
#splitting the dataset
from sklearn.linear_model import LinearRegression

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(df_new_x,y,test_size=0.3,random_state=100)

In [85]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [86]:
#multiple linear regression model

#creating linear regression instance 'mlr'
mlr=LinearRegression()
mlr.fit(x_train,y_train)

ValueError: Input contains NaN

# prediction on the test set

In [ ]:
y_pred_mlr=mlr.predict(x_test)

In [ ]:
print("prediction for test set:{}".format(y_pred_mlr))

In [ ]:
#actual value and the predicted value

mlr_diff=pd.DataFrame({'Actual value': y_test, 'Predicted value': y_pred_mlr})
mlr_diff.head()

# evaluating the model

In [64]:
from sklearn import metrics

In [ ]:
meanAbErr=metrics.mean_absolute_error(y_test,y_pred_mlr)
meanSqErr=metrics.mean_squared_error(y_test,y_pred_mlr)
rootMeanSqErr=np.sqrt(metrics.mean_squared_error(y_test,y_pred_mlr))

print('R squared: {:.2f}'.format(mlr.score(x,y)*100))
print('Mean Absolute Error:', meanAbErr)
print('Mean Square Error:',meanSqErr)
printprint('Root Mean Square Error:', rootMeanSqErr)

In [29]:
!pip install --upgrade tensorflow-gpu

Requirement already up-to-date: tensorflow-gpu in ./newvenv/lib/python3.8/site-packages (2.10.0)
Requirement already satisfied, skipping upgrade: flatbuffers>=2.0 in ./newvenv/lib/python3.8/site-packages (from tensorflow-gpu) (22.10.26)
Requirement already satisfied, skipping upgrade: h5py>=2.9.0 in ./newvenv/lib/python3.8/site-packages (from tensorflow-gpu) (3.7.0)
Requirement already satisfied, skipping upgrade: six>=1.12.0 in ./newvenv/lib/python3.8/site-packages (from tensorflow-gpu) (1.16.0)
Requirement already satisfied, skipping upgrade: tensorboard<2.11,>=2.10 in ./newvenv/lib/python3.8/site-packages (from tensorflow-gpu) (2.10.1)
Requirement already satisfied, skipping upgrade: packaging in ./newvenv/lib/python3.8/site-packages (from tensorflow-gpu) (21.3)
Requirement already satisfied, skipping upgrade: absl-py>=1.0.0 in ./newvenv/lib/python3.8/site-packages (from tensorflow-gpu) (1.3.0)
Requirement already satisfied, skipping upgrade: termcolor>=1.1.0 in ./newvenv/lib/python3.8/site-packages (from tensorflow-gpu) (2.1.0)
Requirement already satisfied, skipping upgrade: tensorflow-io-gcs-filesystem>=0.23.1 in ./newvenv/lib/python3.8/site-packages (from tensorflow-gpu) (0.27.0)
Requirement already satisfied, skipping upgrade: setuptools in ./newvenv/lib/python3.8/site-packages (from tensorflow-gpu) (44.0.0)
Requirement already satisfied, skipping upgrade: libclang>=13.0.0 in ./newvenv/lib/python3.8/site-packages (from tensorflow-gpu) (14.0.6)
Requirement already satisfied, skipping upgrade: typing-extensions>=3.6.6 in ./newvenv/lib/python3.8/site-packages (from tensorflow-gpu) (4.4.0)
Requirement already satisfied, skipping upgrade: wrapt>=1.11.0 in ./newvenv/lib/python3.8/site-packages (from tensorflow-gpu) (1.14.1)
Requirement already satisfied, skipping upgrade: google-pasta>=0.1.1 in ./newvenv/lib/python3.8/site-packages (from tensorflow-gpu) (0.2.0)
Requirement already satisfied, skipping upgrade: gast<=0.4.0,>=0.2.1 in ./newvenv/lib/python3.8/site-packages (from tensorflow-gpu) (0.4.0)
Requirement already satisfied, skipping upgrade: astunparse>=1.6.0 in ./newvenv/lib/python3.8/site-packages (from tensorflow-gpu) (1.6.3)
Requirement already satisfied, skipping upgrade: tensorflow-estimator<2.11,>=2.10.0 in ./newvenv/lib/python3.8/site-packages (from tensorflow-gpu) (2.10.0)
Requirement already satisfied, skipping upgrade: keras<2.11,>=2.10.0 in ./newvenv/lib/python3.8/site-packages (from tensorflow-gpu) (2.10.0)
Requirement already satisfied, skipping upgrade: keras-preprocessing>=1.1.1 in ./newvenv/lib/python3.8/site-packages (from tensorflow-gpu) (1.1.2)
Requirement already satisfied, skipping upgrade: opt-einsum>=2.3.2 in ./newvenv/lib/python3.8/site-packages (from tensorflow-gpu) (3.3.0)
Requirement already satisfied, skipping upgrade: protobuf<3.20,>=3.9.2 in ./newvenv/lib/python3.8/site-packages (from tensorflow-gpu) (3.19.6)
Requirement already satisfied, skipping upgrade: grpcio<2.0,>=1.24.3 in ./newvenv/lib/python3.8/site-packages (from tensorflow-gpu) (1.50.0)
Requirement already satisfied, skipping upgrade: numpy>=1.20 in ./newvenv/lib/python3.8/site-packages (from tensorflow-gpu) (1.23.4)
Requirement already satisfied, skipping upgrade: markdown>=2.6.8 in ./newvenv/lib/python3.8/site-packages (from tensorboard<2.11,>=2.10->tensorflow-gpu) (3.4.1)
Requirement already satisfied, skipping upgrade: werkzeug>=1.0.1 in ./newvenv/lib/python3.8/site-packages (from tensorboard<2.11,>=2.10->tensorflow-gpu) (2.2.2)
Requirement already satisfied, skipping upgrade: google-auth<3,>=1.6.3 in ./newvenv/lib/python3.8/site-packages (from tensorboard<2.11,>=2.10->tensorflow-gpu) (2.14.1)
Requirement already satisfied, skipping upgrade: tensorboard-data-server<0.7.0,>=0.6.0 in ./newvenv/lib/python3.8/site-packages (from tensorboard<2.11,>=2.10->tensorflow-gpu) (0.6.1)
Requirement already satisfied, skipping upgrade: google-auth-oauthlib<0.5,>=0.4.1 in ./newvenv/lib/python3.8/site-packages (from tensorboard<2.11,>=2.10->tensorflow-gpu) (0.4.6)
Requirement already satisfied, skipping upgrade: tensorboard-plugin-wit>=1.6.0 in ./newvenv/lib/python3.8/site-packages (from tensorboard<2.11,>=2.10->tensorflow-gpu) (1.8.1)
Requirement already satisfied, skipping upgrade: wheel>=0.26 in ./newvenv/lib/python3.8/site-packages (from tensorboard<2.11,>=2.10->tensorflow-gpu) (0.38.4)
Requirement already satisfied, skipping upgrade: requests<3,>=2.21.0 in ./newvenv/lib/python3.8/site-packages (from tensorboard<2.11,>=2.10->tensorflow-gpu) (2.28.1)
Requirement already satisfied, skipping upgrade: pyparsing!=3.0.5,>=2.0.2 in ./newvenv/lib/python3.8/site-packages (from packaging->tensorflow-gpu) (3.0.9)
Requirement already satisfied, skipping upgrade: importlib-metadata>=4.4; python_version < "3.10" in ./newvenv/lib/python3.8/site-packages (from markdown>=2.6.8->tensorboard<2.11,>=2.10->tensorflow-gpu) (5.0.0)
Requirement already satisfied, skipping upgrade: MarkupSafe>=2.1.1 in ./newvenv/lib/python3.8/site-packages (from werkzeug>=1.0.1->tensorboard<2.11,>=2.10->tensorflow-gpu) (2.1.1)
Requirement already satisfied, skipping upgrade: pyasn1-modules>=0.2.1 in ./newvenv/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.11,>=2.10->tensorflow-gpu) (0.2.8)
Requirement already satisfied, skipping upgrade: cachetools<6.0,>=2.0.0 in ./newvenv/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.11,>=2.10->tensorflow-gpu) (5.2.0)
Requirement already satisfied, skipping upgrade: rsa<5,>=3.1.4; python_version >= "3.6" in ./newvenv/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.11,>=2.10->tensorflow-gpu) (4.9)
Requirement already satisfied, skipping upgrade: requests-oauthlib>=0.7.0 in ./newvenv/lib/python3.8/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.11,>=2.10->tensorflow-gpu) (1.3.1)
Requirement already satisfied, skipping upgrade: idna<4,>=2.5 in ./newvenv/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard<2.11,>=2.10->tensorflow-gpu) (3.4)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in ./newvenv/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard<2.11,>=2.10->tensorflow-gpu) (2022.9.24)
Requirement already satisfied, skipping upgrade: urllib3<1.27,>=1.21.1 in ./newvenv/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard<2.11,>=2.10->tensorflow-gpu) (1.26.12)
Requirement already satisfied, skipping upgrade: charset-normalizer<3,>=2 in ./newvenv/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard<2.11,>=2.10->tensorflow-gpu) (2.1.1)
Requirement already satisfied, skipping upgrade: zipp>=0.5 in ./newvenv/lib/python3.8/site-packages (from importlib-metadata>=4.4; python_version < "3.10"->markdown>=2.6.8->tensorboard<2.11,>=2.10->tensorflow-gpu) (3.10.0)
Requirement already satisfied, skipping upgrade: pyasn1<0.5.0,>=0.4.6 in ./newvenv/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.11,>=2.10->tensorflow-gpu) (0.4.8)
Requirement already satisfied, skipping upgrade: oauthlib>=3.0.0 in ./newvenv/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.11,>=2.10->tensorflow-gpu) (3.2.2)

In [30]:
!pip install --upgrade keras

Requirement already up-to-date: keras in ./newvenv/lib/python3.8/site-packages (2.10.0)

In [32]:
# Python ≥3.5 is required
import sys
assert sys.version_info >= (3, 5)

# Is this notebook running on Colab or Kaggle?
IS_COLAB = "google.colab" in sys.modules
IS_KAGGLE = "kaggle_secrets" in sys.modules

# Scikit-Learn ≥0.20 is required
import sklearn
assert sklearn.__version__ >= "0.20"

# TensorFlow ≥2.0 is required
import tensorflow as tf
from tensorflow import keras
assert tf.__version__ >= "2.0"

if not tf.config.list_physical_devices('GPU'):
    print("No GPU was detected. LSTMs and CNNs can be very slow without a GPU.")
    if IS_COLAB:
        print("Go to Runtime > Change runtime and select a GPU hardware accelerator.")
    if IS_KAGGLE:
        print("Go to Settings > Accelerator and select GPU.")

# Common imports
import numpy as np
import os

# to make this notebook's output stable across runs
np.random.seed(42)
tf.random.set_seed(42)

# To plot pretty figures
%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.rc('axes', labelsize=14)
mpl.rc('xtick', labelsize=12)
mpl.rc('ytick', labelsize=12)

# Where to save the figures
PROJECT_ROOT_DIR = "."
CHAPTER_ID = "autoencoders"
IMAGES_PATH = os.path.join(PROJECT_ROOT_DIR, "images", CHAPTER_ID)
os.makedirs(IMAGES_PATH, exist_ok=True)

def save_fig(fig_id, tight_layout=True, fig_extension="png", resolution=300):
    path = os.path.join(IMAGES_PATH, fig_id + "." + fig_extension)
    print("Saving figure", fig_id)
    if tight_layout:
        plt.tight_layout()
    plt.savefig(path, format=fig_extension, dpi=resolution)

# GAN

In [1]:
np.random.seed(42)
tf.random.set_seed(42)

codings_size = 30

generator = keras.models.Sequential([
    keras.layers.Dense(100, activation="selu", input_shape=[codings_size]),
    keras.layers.Dense(150, activation="selu"),
    keras.layers.Dense(28 * 28, activation="sigmoid"),
    keras.layers.Reshape([28, 28])
])
discriminator = keras.models.Sequential([
    keras.layers.Flatten(input_shape=[28, 28]),
    keras.layers.Dense(150, activation="selu"),
    keras.layers.Dense(100, activation="selu"),
    keras.layers.Dense(1, activation="sigmoid")
])
gan = keras.models.Sequential([generator, discriminator])

NameError: name 'np' is not defined

In [150]:
discriminator.compile(loss="binary_crossentropy", optimizer="rmsprop")
discriminator.trainable = False
gan.compile(loss="binary_crossentropy", optimizer="rmsprop")

In [151]:
train_gan(gan, dataset, batch_size, codings_size, n_epochs=1)

Epoch 1/1

2022-11-13 13:09:32.561760: E tensorflow/stream_executor/cuda/cuda_blas.cc:218] failed to create cublas handle: cublas error
2022-11-13 13:09:32.561784: E tensorflow/stream_executor/cuda/cuda_blas.cc:220] Failure to initialize cublas may be due to OOM (cublas needs some free memory when you initialize it, and your deep-learning framework may have preallocated more than its fair share), or may be because this binary was not built with support for the GPU in your machine.
2022-11-13 13:09:32.561797: W tensorflow/core/framework/op_kernel.cc:1780] OP_REQUIRES failed at matmul_op_impl.h:620 : INTERNAL: Attempting to perform BLAS operation using StreamExecutor without BLAS support

InternalError: Exception encountered when calling layer "dense_12" "                 f"(type Dense).

{{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:GPU:0}} Attempting to perform BLAS operation using StreamExecutor without BLAS support [Op:MatMul]

Call arguments received by layer "dense_12" "                 f"(type Dense):
  • inputs=tf.Tensor(shape=(32, 30), dtype=float32)

In [141]:
train_gan(gan, dataset, batch_size, codings_size)

Epoch 1/50

2022-11-13 12:56:06.403412: E tensorflow/stream_executor/cuda/cuda_blas.cc:218] failed to create cublas handle: cublas error
2022-11-13 12:56:06.403432: E tensorflow/stream_executor/cuda/cuda_blas.cc:220] Failure to initialize cublas may be due to OOM (cublas needs some free memory when you initialize it, and your deep-learning framework may have preallocated more than its fair share), or may be because this binary was not built with support for the GPU in your machine.
2022-11-13 12:56:06.403445: W tensorflow/core/framework/op_kernel.cc:1780] OP_REQUIRES failed at matmul_op_impl.h:620 : INTERNAL: Attempting to perform BLAS operation using StreamExecutor without BLAS support

InternalError: Exception encountered when calling layer "dense_6" "                 f"(type Dense).

{{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:GPU:0}} Attempting to perform BLAS operation using StreamExecutor without BLAS support [Op:MatMul]

Call arguments received by layer "dense_6" "                 f"(type Dense):
  • inputs=tf.Tensor(shape=(32, 30), dtype=float32)

# multi-linear regression

## unique values in each columns

In [51]:
#unique values in each columns

for x in df.columns:
    #printing unique values
    print(x,':', len(df[x].unique()))

country code and phase : 62
year of interview : 15
URBAN_RURA : 3
region : 395
source of drinking water (simplified) : 16
time to get to water source (minutes) : 280
location of source for water : 4
source of drinking water (categorized by type) : 9

In [32]:
df['GEID'].value_counts()

NGGE7BFL    40427
NGGE6AFL    38522
KEGE71FL    36430
EGGE61FL    28175
MWGE7AFL    26361
            ...
GNGE81FL     3985
MWGE7IFL     3729
MWGE71FL     3405
MWGE6AFL     3404
MLGE63FL     1617
Name: GEID, Length: 87, dtype: int64

In [33]:
# find the top 10 most frequent categories
df.GEID.value_counts().sort_values(ascending=False).head(10)

NGGE7BFL    40427
NGGE6AFL    38522
KEGE71FL    36430
EGGE61FL    28175
MWGE7AFL    26361
GHGE7IFL    26324
MWGE62FL    24825
UGGE7AFL    19588
CDGE61FL    18171
BJGE61FL    17422
Name: GEID, dtype: int64

# dummy encoder

In [34]:
df_ohe=pd.get_dummies(df)
print(df_ohe)

        year of interview  time to get to water source (minutes)  \
0                  2011.0                                    NaN
1                  2011.0                                    NaN
2                  2011.0                                    NaN
3                  2011.0                                    NaN
4                  2011.0                                    NaN
...                   ...                                    ...
970631             2015.0                                    0.0
970632             2015.0                                    0.0
970633             2015.0                                   10.0
970634             2015.0                                    0.0
970635             2015.0                                   10.0

        GEID_AOGE61FL  GEID_AOGE71FL  GEID_BFGE61FL  GEID_BFGE71FL  \
0                   1              0              0              0
1                   1              0              0              0
2                   1              0              0              0
3                   1              0              0              0
4                   1              0              0              0
...               ...            ...            ...            ...
970631              0              0              0              0
970632              0              0              0              0
970633              0              0              0              0
970634              0              0              0              0
970635              0              0              0              0

        GEID_BFGE7AFL  GEID_BJGE61FL  GEID_BJGE71FL  GEID_BUGE61FL  ...  \
0                   0              0              0              0  ...
1                   0              0              0              0  ...
2                   0              0              0              0  ...
3                   0              0              0              0  ...
4                   0              0              0              0  ...
...               ...            ...            ...            ...  ...
970631              0              0              0              0  ...
970632              0              0              0              0  ...
970633              0              0              0              0  ...
970634              0              0              0              0  ...
970635              0              0              0              0  ...

        location of source for water_in own dwelling  \
0                                                  0
1                                                  0
2                                                  0
3                                                  0
4                                                  0
...                                              ...
970631                                             0
970632                                             0
970633                                             0
970634                                             0
970635                                             0

        location of source for water_in own yard/plot  \
0                                                   0
1                                                   0
2                                                   0
3                                                   0
4                                                   0
...                                               ...
970631                                              1
970632                                              1
970633                                              0
970634                                              1
970635                                              0

        source of drinking water (categorized by type)_bottled  \
0                                                       0
1                                                       0
2                                                       0
3                                                       0
4                                                       0
...                                                   ...
970631                                                  0
970632                                                  0
970633                                                  0
970634                                                  0
970635                                                  0

        source of drinking water (categorized by type)_other  \
0                                                       0
1                                                       0
2                                                       0
3                                                       0
4                                                       0
...                                                   ...
970631                                                  0
970632                                                  0
970633                                                  0
970634                                                  0
970635                                                  0

        source of drinking water (categorized by type)_piped  \
0                                                       1
1                                                       1
2                                                       1
3                                                       1
4                                                       1
...                                                   ...
970631                                                  0
970632                                                  0
970633                                                  0
970634                                                  0
970635                                                  0

        source of drinking water (categorized by type)_spring  \
0                                                       0
1                                                       0
2                                                       0
3                                                       0
4                                                       0
...                                                   ...
970631                                                  0
970632                                                  0
970633                                                  0
970634                                                  0
970635                                                  0

        source of drinking water (categorized by type)_street vendor  \
0                                                       0
1                                                       0
2                                                       0
3                                                       0
4                                                       0
...                                                   ...
970631                                                  0
970632                                                  0
970633                                                  0
970634                                                  0
970635                                                  0

        source of drinking water (categorized by type)_surface water  \
0                                                       0
1                                                       0
2                                                       0
3                                                       0
4                                                       0
...                                                   ...
970631                                                  0
970632                                                  0
970633                                                  0
970634                                                  0
970635                                                  0

        source of drinking water (categorized by type)_tube well or borehole  \
0                                                       0
1                                                       0
2                                                       0
3                                                       0
4                                                       0
...                                                   ...
970631                                                  0
970632                                                  0
970633                                                  0
970634                                                  0
970635                                                  0

        source of drinking water (categorized by type)_well
0                                                       0
1                                                       0
2                                                       0
3                                                       0
4                                                       0
...                                                   ...
970631                                                  1
970632                                                  1
970633                                                  1
970634                                                  1
970635                                                  1

[970636 rows x 572 columns]

In [35]:
df_ohe.shape

(970636, 572)

In [36]:
dataset1=[df,df_ohe]

In [37]:
df_new=pd.concat(dataset1,axis=1, join='inner')

In [38]:
df_new

,GEID,country code and phase,year of interview,URBAN_RURA,region,source of drinking water (simplified),time to get to water source (minutes),location of source for water,source of drinking water (categorized by type),year of interview,...,location of source for water_in own dwelling,location of source for water_in own yard/plot,source of drinking water (categorized by type)_bottled,source of drinking water (categorized by type)_other,source of drinking water (categorized by type)_piped,source of drinking water (categorized by type)_spring,source of drinking water (categorized by type)_street vendor,source of drinking water (categorized by type)_surface water,source of drinking water (categorized by type)_tube well or borehole,source of drinking water (categorized by type)_well
0,AOGE61FL,AO5,2011.0,U,mesoendemica estavel,piped into dwelling,NaN,NaN,piped,2011.0,...,0,0,0,0,1,0,0,0,0,0
1,AOGE61FL,AO5,2011.0,U,mesoendemica estavel,piped into dwelling,NaN,NaN,piped,2011.0,...,0,0,0,0,1,0,0,0,0,0
2,AOGE61FL,AO5,2011.0,U,mesoendemica estavel,piped into dwelling,NaN,NaN,piped,2011.0,...,0,0,0,0,1,0,0,0,0,0
3,AOGE61FL,AO5,2011.0,U,mesoendemica estavel,piped into dwelling,NaN,NaN,piped,2011.0,...,0,0,0,0,1,0,0,0,0,0
4,AOGE61FL,AO5,2011.0,U,mesoendemica estavel,piped into dwelling,NaN,NaN,piped,2011.0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970631,ZWGE72FL,ZW7,2015.0,R,mashonaland east,protected well,0.0,in own yard/plot,well,2015.0,...,0,1,0,0,0,0,0,0,0,1
970632,ZWGE72FL,ZW7,2015.0,R,mashonaland east,protected well,0.0,in own yard/plot,well,2015.0,...,0,1,0,0,0,0,0,0,0,1
970633,ZWGE72FL,ZW7,2015.0,R,mashonaland east,unprotected well,10.0,elsewhere,well,2015.0,...,0,0,0,0,0,0,0,0,0,1
970634,ZWGE72FL,ZW7,2015.0,R,mashonaland east,protected well,0.0,in own yard/plot,well,2015.0,...,0,1,0,0,0,0,0,0,0,1
970635,ZWGE72FL,ZW7,2015.0,R,mashonaland east,protected well,10.0,elsewhere,well,2015.0,...,0,0,0,0,0,0,0,0,0,1

In [39]:
df_new.shape

(970636, 581)

# one-hot encoding

In [40]:
from category_encoders.one_hot import OneHotEncoder

In [41]:
#creating instance of one-hot encoder
encoder=OneHotEncoder(handle_unknown='ignore')

In [21]:
ohe=OneHotEncoder(use_cat_names=True)
ohe.fit_transform(df['source of drinking water (simplified)'])

,GEID_AOGE61FL,GEID_AOGE71FL,GEID_BFGE61FL,GEID_BFGE71FL,GEID_BFGE7AFL,GEID_BJGE61FL,GEID_BJGE71FL,GEID_BUGE61FL,GEID_BUGE6AFL,GEID_BUGE71FL,...,location of source for water_in own dwelling,source of drinking water (categorized by type)_piped,source of drinking water (categorized by type)_spring,source of drinking water (categorized by type)_street vendor,source of drinking water (categorized by type)_surface water,source of drinking water (categorized by type)_well,source of drinking water (categorized by type)_bottled,source of drinking water (categorized by type)_tube well or borehole,source of drinking water (categorized by type)_other,source of drinking water (categorized by type)_nan
0,1,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970631,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
970632,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
970633,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
970634,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
970635,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0